# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Vinayak Sonawane blogs

description: I amm diving headfirst into data science and machine learning! 💻✨ I will be sharing my thoughts and learnings right here on the blog. Your suggestions and insights are more than welcome THANK YOU... ❤

github_username: coding4vinayak
website : "coding4vinayak.pythonanywhere.com"

# Email and twitter are optional:
email:  coding4vinayak@gmail.com
twitter_username: "coding4vinayak"
website : "coding4vinayak.pythonanywhere.com"

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: G-GRK65BX801

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
